#!/usr/bin/env node

var childProcess = require('child_process');

var isWin = /^win/.test(process.platform);

var spawn = childProcess.spawn;
var exec = childProcess.execSync;

function getGitCachedFiles (glob) {
    return exec('git diff --cached --name-only --diff-filter=ACMR ' + glob).toString().trim();
}

function spawnNpmScript (command) {
    spawn(isWin ? 'npm.cmd' : 'npm', ['run', command], {stdio: 'inherit'})
      .on('close', process.exit.bind(process));
}

if (getGitCachedFiles('./src/')) {
    if (getGitCachedFiles('*.css')) {
        spawnNpmScript('quality-check');
    } else {
        spawnNpmScript('quality-check-js');
    }
} else if (getGitCachedFiles('./gemini/')) {
    spawnNpmScript('lint-js');
}
