plugins:
  - convertShapeToPath: false
  - mergePaths: false
  - collapseGroups: true
  - moveGroupAttrsToElems: false
  - moveElemsAttrsToGroup: false
  - cleanupListOfValues: false
  - cleanupNumericValues: false
  - cleanupIDs: true
  - removeUnusedNS: true
  - removeUselessStrokeAndFill: false
  - removeNonInheritableGroupAttrs: false
  - removeUnknownsAndDefaults: false
  - convertTransform: false
  - convertPathData: false
  - convertColors: false
  - convertStyleToAttrs: false
  - minifyStyles: false
  - cleanupEnableBackground: false
  - removeViewBox: false
  - removeEmptyContainers: true
  - removeEmptyText: true
  - removeHiddenElems: false
  - removeEmptyAttrs: true
  - removeEditorsNSData: true
  - removeUselessDefs: true
  - removeDesc: true
  - removeTitle: true
  - removeMetadata: true
  - removeComments: true
  - removeXMLProcInst: true
  - removeDoctype: true
  - inlineStyles: false
  - cleanupAttrs: false
